[2024-09-12T02:58:10.142+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T02:58:10.161+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline.load_data_to_gcs manual__2024-09-12T02:57:38.606500+00:00 [queued]>
[2024-09-12T02:58:10.169+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline.load_data_to_gcs manual__2024-09-12T02:57:38.606500+00:00 [queued]>
[2024-09-12T02:58:10.170+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-12T02:58:10.183+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data_to_gcs> on 2024-09-12 02:57:38.606500+00:00
[2024-09-12T02:58:10.191+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=799) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-12T02:58:10.192+0000] {standard_task_runner.py:72} INFO - Started process 800 to run task
[2024-09-12T02:58:10.192+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline', 'load_data_to_gcs', 'manual__2024-09-12T02:57:38.606500+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/f1_to_gcs.py', '--cfg-path', '/tmp/tmpx2pfvm0b']
[2024-09-12T02:58:10.194+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask load_data_to_gcs
[2024-09-12T02:58:10.238+0000] {task_command.py:467} INFO - Running <TaskInstance: f1_data_pipeline.load_data_to_gcs manual__2024-09-12T02:57:38.606500+00:00 [running]> on host ac22af181946
[2024-09-12T02:58:10.309+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T02:57:38.606500+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T02:57:38.606500+00:00'
[2024-09-12T02:58:10.311+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T02:58:36.666+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-12T02:58:36.677+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T02:58:36.686+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline, task_id=load_data_to_gcs, run_id=manual__2024-09-12T02:57:38.606500+00:00, execution_date=20240912T025738, start_date=20240912T025810, end_date=20240912T025836
[2024-09-12T02:58:36.711+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T02:58:36.727+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T02:58:36.729+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
